# Generated by Django 4.0.5 on 2022-07-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('speaker', models.CharField(max_length=256)),
                ('text_en', models.CharField(max_length=4096)),
                ('text_cn_traditional', models.CharField(max_length=4096)),
                ('text_cn_simplified', models.CharField(max_length=4096)),
                ('text_cn_pinyin', models.CharField(max_length=4096)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.conversation')),
            ],
        ),
    ]
