# Generated by Django 4.0.5 on 2022-07-04 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text_cn_pinyin',
            field=models.CharField(max_length=4096, verbose_name='text (pinyin)'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text_cn_simplified',
            field=models.CharField(max_length=4096, verbose_name='text (simplified)'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text_cn_traditional',
            field=models.CharField(max_length=4096, verbose_name='text (traditional)'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text_en',
            field=models.CharField(max_length=4096, verbose_name='text (english)'),
        ),
    ]
