# Generated by Django 4.0.5 on 2022-07-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_conversation_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='name',
            field=models.CharField(default='???', max_length=256),
            preserve_default=False,
        ),
    ]
