# Generated by Django 4.0.5 on 2022-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='name',
            field=models.CharField(default='???', max_length=256),
            preserve_default=False,
        ),
    ]
