# Generated by Django 4.0.5 on 2022-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_sentence_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='view_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
