# Generated by Django 4.0.5 on 2022-07-08 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_conversation_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='view_count',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_viewed', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.conversation')),
            ],
        ),
    ]
