# Generated by Django 4.0.5 on 2022-07-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_conversation_date_viewed_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('start_ms', models.IntegerField(null=True, verbose_name='start (ms)')),
                ('end_ms', models.IntegerField(null=True, verbose_name='end (ms)')),
                ('text_en', models.CharField(max_length=4096, verbose_name='text (english)')),
                ('text_cn_traditional', models.CharField(max_length=4096, verbose_name='text (traditional)')),
                ('text_cn_simplified', models.CharField(max_length=4096, null=True, verbose_name='text (simplified)')),
                ('text_cn_pinyin', models.CharField(max_length=4096, verbose_name='text (pinyin)')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256, null=True)),
                ('url', models.CharField(max_length=2048, null=True)),
                ('date_published', models.DateTimeField(null=True)),
                ('date_added', models.DateTimeField()),
                ('date_viewed', models.DateTimeField(null=True)),
            ],
        ),
    ]
