# Generated by Django 4.0.5 on 2022-07-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_entry_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='transcript',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='practice.transcript'),
            preserve_default=False,
        ),
    ]
