# Generated by Django 4.0.5 on 2022-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_entry_transcript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='date_viewed',
            new_name='last_viewed',
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='date_published',
            field=models.DateField(null=True),
        ),
    ]
