# Generated by Django 4.0.5 on 2022-07-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0010_rename_date_viewed_transcript_last_viewed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('source', models.CharField(max_length=256)),
                ('text_cn_traditional', models.CharField(max_length=4096, verbose_name='text (traditional)')),
                ('text_cn_simplified', models.CharField(max_length=4096, null=True, verbose_name='text (simplified)')),
                ('text_cn_pinyin', models.CharField(max_length=4096, verbose_name='text (pinyin)')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.entry')),
            ],
        ),
    ]
