# Generated by Django 4.0.5 on 2022-07-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_alter_entry_options_alter_translation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
