# Generated by Django 4.0.5 on 2022-07-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0014_entry_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text_en',
            field=models.TextField(verbose_name='text (english)'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_cn_pinyin',
            field=models.TextField(verbose_name='text (pinyin)'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_cn_simplified',
            field=models.TextField(null=True, verbose_name='text (simplified)'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='text_cn_traditional',
            field=models.TextField(verbose_name='text (traditional)'),
        ),
    ]
