# Generated by Django 4.0.5 on 2022-07-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0015_alter_entry_notes_alter_entry_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'E'), (2, 'M'), (3, 'H')], null=True),
        ),
    ]
