# Generated by Django 4.0.5 on 2022-07-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0016_entry_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=0),
        ),
    ]
