# Generated by Django 4.0.5 on 2022-07-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0017_alter_entry_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('translation', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('entries', models.ManyToManyField(to='practice.entry')),
            ],
        ),
    ]
