# Generated by Django 4.0.5 on 2022-07-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0018_vocab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
