# Generated by Django 4.0.5 on 2022-07-17 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0020_remove_vocab_date_created_vocab_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocab',
            name='time_last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
