# Generated by Django 4.0.5 on 2022-07-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0021_vocab_time_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vocab',
            options={'ordering': ['-time_last_modified']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='difficulty',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=0),
        ),
    ]
